server:
  port: 80

spring:
  application:
    name: cloud-order-service
  profiles:
    active: dev

# 配置 Eureka Client
eureka:
  client:
    # 表示是否将自己注册到 Eureka Server 中，true为默认值
    register-with-eureka: true
    # 是否从 Eureka Server 抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7003.com:7003/eureka     # 集群版
