server:
  port: 8001

spring:
  application:
    name: cloud-payment-sevice    # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 数据源
    driver-class-name: com.mysql.jdbc.Driver      # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  # 激活的环境
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml        # 配置mapper.xml位置
  type-aliases-package: com.scy.entities          # 所有Entity别名类所在的包
